version: '2'
#version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./docker/nginx/symfony_web_contao_manager.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"
        #environment:
            #- NGINX_HOST=${NGINX_HOST}
            #- APP_DEV_ACCESSKEY=${APP_DEV_ACCESSKEY}
        #restart: always
        depends_on:
            - php
            - db
        volumes_from:
            - php
    php:
        #build:
        #   context: .
        #   dockerfile: Dockerfile.development

        build: ./docker/php-fpm
        env_file:
            - ".env"
        environment:
            - APP_DEV_ACCESSKEY=${APP_DEV_ACCESSKEY}
        volumes:
            - "./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini"

    db:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - contao-mysql-data:/var/lib/mysql
            #- "./data/db/mysql:/var/lib/mysql"

volumes:
  contao-mysql-data:
    driver: local